services:
  postgres:
    image: postgres:16-alpine
    container_name: mini-erp-crm-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_erp_crm
    ports:
      - "5433:5432"
    volumes:
      - mini_erp_crm_pgdata:/var/lib/postgresql/data

volumes:
  mini_erp_crm_pgdata:
