import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Badge, Button, DataTable, FormInput, LoadingSpinner, Pagination, Select } from "../components";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import { listCustomers } from "../services/customer.service";
import { createChallan, getChallan, listChallans, confirmChallan, cancelChallan } from "../services/challan.service";
import { listProducts } from "../services/product.service";
import type { Challan, Customer, Product, Pagination as PageInfo } from "../types";
import { formatDate } from "../utils/format";

export function ChallansPage(){
 const {notify}=useToast(); const [items,setItems]=useState<Challan[]>([]); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true); const [pagination,setPagination]=useState<PageInfo>({page:1,limit:10,total:0,totalPages:1});
 async function load(){setLoading(true);try{const r=await listChallans({page,limit:10,search:search||undefined,status:status||undefined});setItems(r.items);setPagination(r.pagination)}catch(e){notify((e as Error).message,"error")}finally{setLoading(false)}}
 useEffect(()=>{load()},[page,search,status]);
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-slate-500">{pagination.total} records</p><h2 className="text-xl font-semibold">Sales challans</h2></div><Link to="/challans/new"><Button>+ Create challan</Button></Link></div>
 <div className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4 shadow-sm"><FormInput label="Search" placeholder="Challan or customer" value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}}/><Select label="Status" value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}} options={[{label:"All statuses",value:""},{label:"Draft",value:"DRAFT"},{label:"Confirmed",value:"CONFIRMED"},{label:"Cancelled",value:"CANCELLED"}]}/></div>
 <div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<LoadingSpinner/>:<DataTable columns={[{key:"number",header:"Challan",render:c=><Link className="font-semibold text-teal-700" to={`/challans/${c.id}`}>{c.challanNumber}</Link>},{key:"customer",header:"Customer",render:c=><span>{c.customer?.businessName||c.customer?.name}</span>},{key:"qty",header:"Qty",render:c=><span>{c.totalQuantity}</span>},{key:"status",header:"Status",render:c=><Badge value={c.status}/>},{key:"date",header:"Created",render:c=><span>{formatDate(c.createdAt)}</span>},{key:"by",header:"Created by",render:c=><span>{c.creator?.name||"—"}</span>}]} data={items} emptyMessage="No challans found"/>}</div><Pagination {...pagination} onChange={setPage}/></div>
}

export function ChallanFormPage(){
 const nav=useNavigate(); const {notify}=useToast(); const [customers,setCustomers]=useState<Customer[]>([]); const [products,setProducts]=useState<Product[]>([]); const [customerId,setCustomerId]=useState(""); const [rows,setRows]=useState<Array<{productId:string;quantity:number}>>([{productId:"",quantity:1}]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([listCustomers({page:1,limit:100}),listProducts({page:1,limit:100})]).then(([c,p])=>{setCustomers(c.items);setProducts(p.items)}).catch(e=>notify((e as Error).message,"error")).finally(()=>setLoading(false))},[]);
 function updateRow(i:number,key:"productId"|"quantity",value:string){setRows(r=>r.map((x,j)=>j===i?{...x,[key]:key==="quantity"?Number(value):value}:x))}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);if(!customerId||rows.some(r=>!r.productId||r.quantity<1)){notify("Select customer, product and valid quantities","error");return}try{const c=await createChallan({customerId,items:rows});notify(`Draft ${c.challanNumber} created`,"success");nav(`/challans/${c.id}`)}catch(e){notify((e as Error).message,"error")}finally{setSaving(false)}}
 if(loading)return <LoadingSpinner/>; return <form onSubmit={submit} className="max-w-4xl space-y-5"><div><h2 className="text-2xl font-semibold">Create sales challan</h2><p className="text-sm text-slate-500">Create a draft first. Confirming it reduces stock.</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><Select label="Customer" value={customerId} onChange={e=>setCustomerId(e.target.value)} options={[{label:"Select customer",value:""},...customers.map(c=>({label:`${c.businessName} — ${c.name}`,value:c.id}))]} required/></div>
 <div className="space-y-3 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><h3 className="font-semibold">Products</h3><Button type="button" variant="secondary" onClick={()=>setRows(r=>[...r,{productId:"",quantity:1}])}>+ Add item</Button></div>{rows.map((r,i)=><div key={i} className="grid gap-3 sm:grid-cols-[1fr_150px_auto]"><Select label={`Product ${i+1}`} value={r.productId} onChange={e=>updateRow(i,"productId",e.target.value)} options={[{label:"Select product",value:""},...products.map(p=>({label:`${p.name} (${p.currentStock} in stock)`,value:p.id}))]}/><FormInput label="Quantity" type="number" min="1" value={String(r.quantity)} onChange={e=>updateRow(i,"quantity",e.target.value)}/>{rows.length>1&&<Button type="button" variant="danger" className="self-end" onClick={()=>setRows(r=>r.filter((_,j)=>j!==i))}>Remove</Button>}</div>)}</div><div className="flex gap-2"><Link to="/challans"><Button type="button" variant="secondary">Cancel</Button></Link><Button disabled={saving}>{saving?"Saving...":"Save draft"}</Button></div></form>
}

export function ChallanDetailPage(){
 const {id}=useParams(); const {user}=useAuth(); const {notify}=useToast(); const [c,setC]=useState<Challan|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
 async function load(){try{if(id)setC(await getChallan(id))}catch(e){notify((e as Error).message,"error")}finally{setLoading(false)}} useEffect(()=>{load()},[id]);
 if(loading)return <LoadingSpinner/>; if(!c)return <p>Challan not found.</p>;
 async function action(fn:()=>Promise<Challan>,message:string){setBusy(true);try{await fn();notify(message,"success");load()}catch(e){notify((e as Error).message,"error")}finally{setBusy(false)}}
 const total=(c.items||[]).reduce((s,i)=>s+Number(i.unitPriceSnapshot)*i.quantity,0);
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><Link className="text-sm text-teal-700" to="/challans">← Challans</Link><h2 className="mt-2 text-2xl font-semibold">{c.challanNumber}</h2><p className="text-slate-500">{c.customer?.businessName} · {formatDate(c.createdAt)}</p></div><div className="flex gap-2">{c.status==="DRAFT"&&user?.role!=="ACCOUNTS"&&<><Button disabled={busy} onClick={()=>action(()=>confirmChallan(c.id),"Challan confirmed and stock reduced")}>Confirm</Button><Button variant="danger" disabled={busy} onClick={()=>action(()=>cancelChallan(c.id),"Challan cancelled")}>Cancel</Button></>}</div></div>
 <div className="grid gap-4 sm:grid-cols-3"><Metric label="Status" value={c.status}/><Metric label="Total quantity" value={String(c.totalQuantity)}/><Metric label="Total value" value={`₹${total.toLocaleString("en-IN")}`}/></div>
 <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="p-5"><h3 className="font-semibold">Line items</h3></div><DataTable columns={[{key:"product",header:"Product",render:i=><span className="font-medium">{i.productNameSnapshot}</span>},{key:"sku",header:"SKU",render:i=><span>{i.skuSnapshot}</span>},{key:"qty",header:"Qty",render:i=><span>{i.quantity}</span>},{key:"price",header:"Unit price",render:i=><span>₹{Number(i.unitPriceSnapshot).toLocaleString("en-IN")}</span>},{key:"amount",header:"Amount",render:i=><span>₹{(Number(i.unitPriceSnapshot)*i.quantity).toLocaleString("en-IN")}</span>}]} data={c.items||[]}/></section>
 <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Customer</h3><p className="mt-3 text-sm">{c.customer?.name}</p><p className="text-sm text-slate-500">{c.customer?.mobile}</p><p className="text-sm text-slate-500">{c.customer?.address}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Audit</h3><p className="mt-3 text-sm">Created by {c.creator?.name||"—"}</p><p className="text-sm text-slate-500">{formatDate(c.createdAt)}</p></div></section></div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 font-semibold">{value}</p></div>}
