import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Badge, Button, DataTable, FormInput, LoadingSpinner, Pagination, Select } from "../components";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import { adjustStock, createProduct, getProduct, listMovements, listProducts, updateProduct } from "../services/product.service";
import type { Pagination as PageInfo, Product, StockMovement } from "../types";
import { formatDate } from "../utils/format";

export function ProductsPage(){
 const {notify}=useToast(); const {user}=useAuth(); const [items,setItems]=useState<Product[]>([]); const [page,setPage]=useState(1); const [search,setSearch]=useState(""); const [low,setLow]=useState(""); const [loading,setLoading]=useState(true); const [pagination,setPagination]=useState<PageInfo>({page:1,limit:10,total:0,totalPages:1});
 async function load(){setLoading(true);try{const r=await listProducts({page,limit:10,search:search||undefined,lowStock:low==="true"?true:undefined});setItems(r.items);setPagination(r.pagination)}catch(e){notify((e as Error).message,"error")}finally{setLoading(false)}}
 useEffect(()=>{load()},[page,search,low]); 
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-slate-500">{pagination.total} SKUs</p><h2 className="text-xl font-semibold">Product catalogue</h2></div>{(user?.role==="ADMIN"||user?.role==="WAREHOUSE")&&<Link to="/products/new"><Button>+ Add product</Button></Link>}</div>
 <div className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4 shadow-sm"><FormInput label="Search" placeholder="Name, SKU or category" value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}}/><Select label="Stock filter" value={low} onChange={e=>{setPage(1);setLow(e.target.value)}} options={[{label:"All products",value:""},{label:"Low stock only",value:"true"}]}/></div>
 <div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<LoadingSpinner/>:<DataTable columns={[
 {key:"name",header:"Product",render:p=><Link className="font-semibold text-teal-700" to={`/products/${p.id}`}>{p.name}</Link>},{key:"sku",header:"SKU",render:p=><span>{p.sku}</span>},{key:"category",header:"Category",render:p=><span>{p.category}</span>},{key:"price",header:"Unit price",render:p=><span>₹{Number(p.unitPrice).toLocaleString("en-IN")}</span>},{key:"stock",header:"Stock",render:p=><span className={p.currentStock<=p.minimumStock?"font-semibold text-rose-700":""}>{p.currentStock}</span>},{key:"status",header:"Status",render:p=><Badge value={p.currentStock<=p.minimumStock?"LOW_STOCK":"IN_STOCK"}/>}
 ]} data={items} emptyMessage="No products found"/>}</div><Pagination {...pagination} onChange={setPage}/></div>
}

export function InventoryPage(){
 const {notify}=useToast(); const [items,setItems]=useState<Product[]>([]); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<Product|null>(null); const [qty,setQty]=useState("1"); const [type,setType]=useState<"IN"|"OUT">("IN"); const [reason,setReason]=useState("");
 async function load(){try{const r=await listProducts({page:1,limit:100});setItems(r.items)}catch(e){notify((e as Error).message,"error")}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 async function submit(e:FormEvent){e.preventDefault();if(!selected)return;try{await adjustStock(selected.id,{quantity:Number(qty),movementType:type,reason});notify("Stock updated","success");setSelected(null);setReason("");load()}catch(e){notify((e as Error).message,"error")}}
 return <div className="space-y-5"><div><p className="text-sm text-slate-500">Warehouse control</p><h2 className="text-xl font-semibold">Inventory</h2></div><div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<LoadingSpinner/>:<DataTable columns={[{key:"name",header:"Product",render:p=><span className="font-semibold">{p.name}</span>},{key:"sku",header:"SKU",render:p=><span>{p.sku}</span>},{key:"location",header:"Location",render:p=><span>{p.warehouseLocation}</span>},{key:"stock",header:"Current",render:p=><span className={p.currentStock<=p.minimumStock?"font-bold text-rose-700":"font-semibold"}>{p.currentStock}</span>},{key:"min",header:"Minimum",render:p=><span>{p.minimumStock}</span>},{key:"action",header:"Action",render:p=><Button variant="secondary" onClick={()=>setSelected(p)}>Adjust</Button>}] } data={items}/>}</div>
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><form onSubmit={submit} className="w-full max-w-md space-y-4 rounded-2xl bg-white p-6 shadow-xl"><h3 className="text-lg font-semibold">Adjust {selected.name}</h3><Select label="Movement" value={type} onChange={e=>setType(e.target.value as "IN"|"OUT")} options={[{label:"Stock IN",value:"IN"},{label:"Stock OUT",value:"OUT"}]}/><FormInput label="Quantity" type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)} required/><FormInput label="Reason" value={reason} onChange={e=>setReason(e.target.value)} required/><div className="flex gap-2"><Button type="button" variant="secondary" onClick={()=>setSelected(null)}>Cancel</Button><Button>Save movement</Button></div></form></div>}</div>
}

export function ProductFormPage(){
 const {id}=useParams(); const nav=useNavigate(); const {notify}=useToast(); const [form,setForm]=useState({name:"",sku:"",category:"",unitPrice:"",currentStock:"0",minimumStock:"0",warehouseLocation:""}); const [loading,setLoading]=useState(!!id);
 useEffect(()=>{if(id)getProduct(id).then(p=>setForm({name:p.name,sku:p.sku,category:p.category,unitPrice:String(p.unitPrice),currentStock:String(p.currentStock),minimumStock:String(p.minimumStock),warehouseLocation:p.warehouseLocation})).catch(e=>notify((e as Error).message,"error")).finally(()=>setLoading(false))},[id]);
 const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v})); async function submit(e:FormEvent){e.preventDefault();try{const payload={...form,unitPrice:Number(form.unitPrice),currentStock:Number(form.currentStock),minimumStock:Number(form.minimumStock)}; if(id)await updateProduct(id,payload);else await createProduct(payload);notify(id?"Product updated":"Product created","success");nav(id?`/products/${id}`:"/products")}catch(e){notify((e as Error).message,"error")}}
 if(loading)return <LoadingSpinner/>; return <form onSubmit={submit} className="max-w-4xl space-y-5"><h2 className="text-2xl font-semibold">{id?"Edit product":"Add product"}</h2><div className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-2">{(["name","sku","category","unitPrice","currentStock","minimumStock","warehouseLocation"] as const).map(k=><FormInput key={k} label={k.replace(/([A-Z])/g," $1")} type={["unitPrice","currentStock","minimumStock"].includes(k)?"number":"text"} value={form[k]} onChange={e=>set(k,e.target.value)} required/>)}</div><div className="flex gap-2"><Link to="/products"><Button variant="secondary">Cancel</Button></Link><Button>Save product</Button></div></form>
}

export function ProductDetailPage(){
 const {id}=useParams(); const {notify}=useToast(); const {user}=useAuth(); const [p,setP]=useState<Product|null>(null); const [moves,setMoves]=useState<StockMovement[]>([]); const [loading,setLoading]=useState(true);
 async function load(){try{if(!id)return;setP(await getProduct(id));setMoves((await listMovements(id,{page:1,limit:20})).items)}catch(e){notify((e as Error).message,"error")}finally{setLoading(false)}} useEffect(()=>{load()},[id]);
 if(loading)return <LoadingSpinner/>; if(!p)return <p>Product not found.</p>;
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><Link className="text-sm text-teal-700" to="/products">← Products</Link><h2 className="mt-2 text-2xl font-semibold">{p.name}</h2><p className="text-slate-500">{p.sku} · {p.category}</p></div>{(user?.role==="ADMIN"||user?.role==="WAREHOUSE")&&<Link to={`/products/${p.id}/edit`}><Button variant="secondary">Edit</Button></Link>}</div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Current stock" value={String(p.currentStock)}/><Metric label="Minimum" value={String(p.minimumStock)}/><Metric label="Unit price" value={`₹${Number(p.unitPrice).toLocaleString("en-IN")}`}/><Metric label="Location" value={p.warehouseLocation}/></div>
 <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="p-5"><h3 className="font-semibold">Stock movement log</h3></div><DataTable columns={[{key:"date",header:"Date",render:m=><span>{formatDate(m.createdAt)}</span>},{key:"type",header:"Type",render:m=><Badge value={m.movementType}/>},{key:"qty",header:"Quantity",render:m=><span>{m.quantity}</span>},{key:"reason",header:"Reason",render:m=><span>{m.reason}</span>},{key:"by",header:"Created by",render:m=><span>{m.creator?.name||"—"}</span>}]} data={moves} emptyMessage="No stock movements"/></section></div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 font-semibold text-navy-900">{value}</p></div>}
